### ISSUE TITLE
Creating PHP Client

### ISSUE THREAD

**Issue by zsaraf** [airbnb/hypernova#16]
Hello,

I'm working on creating a php client for hypernova. One thing that I haven't been able to figure out is what url to post to for hypernova, and how the POST params should be set up. I'm running hypernova.js locally, and have tried POST'ing to http://localhost:3030/ but am getting 404s! When I POST to http://localhost:3030/batch I get this response (below), no matter what i put in the params, and `getComponent` is not being called.

`{
  "success": true,
  "error": null,
  "results": {}
}`

I would appreciate a little bit more information on what the POST url is and how POST params should be passed.

**Comment by goatslacker** [comment]
Sure. 

The `HOST` is whatever you're running Hypernova on `localhost` usually works if you're testing locally.
`PORT` is whatever is specified when you setup Hypernova. You can see an example here in the [README](https://github.com/airbnb/hypernova#node) and there's also [this working example](https://github.com/airbnb/hypernova/blob/master/examples/simple/hypernova.js#L13).

The URL is `/batch` and that's just because that's what it was named. It's the [only route](https://github.com/airbnb/hypernova/blob/master/src/worker.js#L21) that is defined for express.

So the full URL would be something like `http://localhost:3030/batch`

The `POST` to `/batch` should look something like:

```js
{
  "NameOfComponent": {
    "name": "NameOfComponent",
    "data": {
      "theseAreProps": true,
      "someOtherProps": ["one", "two", "three"]
    },
  }
}
```

If `"NameOfComponent"` exists and [`getComponent`](https://github.com/airbnb/hypernova#getcomponent) returns it then you should see stuff happening.

Also, I'd be super excited for a php client :)

**Comment by zsaraf** [comment]
Thanks a lot!

**Comment by zsaraf** [comment]
I'd also recommend putting the above info ^^ that you provided me in the client spec (https://github.com/airbnb/hypernova/blob/master/docs/client-spec.md) as it is very important and not directly specified anywhere. People will definitely find that info helpful when creating their own clients :-)

**Comment by goatslacker** [comment]
SGTM, I'll open a PR.

**Comment by abelmokadem** [comment]
@zsaraf is there a public repo of the work you have done?

**Comment by nickyr** [comment]
looks like someone else did one: https://github.com/wayfair/hypernova-php
