### ISSUE TITLE
devMode does not reload the components / invalidate the require cache

### ISSUE THREAD

**Issue by Inkdpixels** [airbnb/hypernova#87]
I just tried out the hypernova stack and found that the `devMode` does not reload the component on each request as [documented](https://github.com/airbnb/hypernova#server).

#### Example
`hypernova.js`
```js
const hypernova = require('hypernova/server');

hypernova({
  devMode: true,
  port: 3030,
  getComponent: name => require(`./${name}.js`)
});
```

`app.js`
```js
const React = require('react');
const {renderReact} = require('hypernova-react');

function App(props) {
  return React.createElement('div', null, `Hello ${props.name}`);
}

module.exports = renderReact('app', App);
```

`server.js`
```js
const express = require('express');
const Renderer = require('hypernova-client');
const devModePlugin = require('hypernova-client/plugins/devModePlugin');

const app = express();

const renderer = new Renderer({
  url: 'http://localhost:3030/batch',
  plugins: [
    devModePlugin,
  ],
});

app.get('/', (req, res) => {
  const jobs = {
    app: { name: req.query.name || 'Stranger' }
  };

  renderer.render(jobs).then(html => res.send(html));
});

app.listen(8080, () => console.log('Now listening'));
```

#### What happens
When requesting `localhost:8080` you will be greeted as configured by `Hello Stranger` but when changing the returned string of the App, e.g. into `Hello foo bar ${props.name}` the supernova server still renders the old cached component and returns `Hello stranger` again.

#### What should happen
When passing a truthy `devMode` option to hypernova, the server should invalidate the Node caches on each request.

I also searched for references of `devMode` in the server code, but haven't found anything [except for the cluster setup](https://github.com/airbnb/hypernova/search?l=JavaScript&q=devMode&type=&utf8=%E2%9C%93). 

Maybe I just missed something, but to me it seems this functionality isn't implemented or was removed in a recent commit?

**Comment by tanraya** [comment]
Same question

**Comment by liang3404814** [comment]
Modules are cached after the first time they are loaded in node. The documentation states this explicitly: 

> The simplest getComponent would be to use require. One drawback here is that your components would be cached between requests and thus could leak memory and/or data. Another drawback is that the files would have to exist relative to where this require is being used.

**Comment by Inkdpixels** [comment]
@liang3404814 Sure but the [docs also state that](https://github.com/airbnb/hypernova#server) `devMode: true` `disables cluster mode and reloads each component every time it is requested`. As I said, maybe I got it all wrong and there is a solution built in (maybe without using require as you stated), but AFAIK devMode is not used besides the cluster setup, so either

1. The docs need to be updated
2. The devMode should handle clearing the require cache or provide an example on how to do this properly?

:)

**Comment by goatslacker** [comment]
Whoops! This is carried over from before this library was open sourced when we had a feature like that. This is no longer useful because you can define your own custom behavior in `getComponent` and even return a Promise from it if you need to asynchronously fetch the file from somewhere. Hypernova also ships with a VM you can use to load remote code.

**Comment by earksiinni** [comment]
In case anyone else came here from Google, here's what I did to disable caching in development:

```
const { createGetComponent } = require('hypernova/server');
const fetch = require('isomorphic-fetch');
const hypernova = require('hypernova/server');
const HypernovaModule = require('hypernova/lib/Module');
const path = require('path');

let getComponent;

if (process.env.NODE_ENV === 'development') {
  // Points to a bundle served by webpack-dev-server
  const filePath = 'http://localhost:8081/ssr-bundle.js';

  // Use custom getComponent that doesn't cache the module
  getComponent = async () => {
    const res = await fetch(filePath);
    const code = await res.text();
    // Alternatively, read the file synchronously from your filesystem
    // fs.readFileSync(filePath)
    const module = new HypernovaModule(filePath);

    module._compile(code, filePath);

    return module.exports;
  };
} else {
  const filePath = '/my/absolute/path.js';

  // Generate standard getComponent that caches the module
  getComponent = createGetComponent({
    application: filePath,
  });
}

hypernova({
  devMode: (process.env.NODE_ENV) === 'development',
  getComponent,
  port: 3030,
});
```

The lines below are where the magic happens:

```
const HypernovaModule = require('hypernova/lib/Module');
const module = new HypernovaModule(filePath);

module._compile(code, filePath);
return module.exports;
```

- `'hypernova/lib/Module'` is Hypernova's implementation of the Node module API. Crucially, it differs internally by invoking `vm.runInNewContext`, which is what allows each rendering to be isolated.
- `module._compile` executes your code in the same way that your code would be executed if you were to call `require` to load a module the normal way. The key difference is that Node's normal `require` call will also execute `module.load`, which caches the module. We _don't_ want caching, so we simply call `module._compile`. ([This link is very helpful if you want to understand how require, load and _compile work](http://fredkschott.com/post/2014/06/require-and-the-module-system/).)
- `return module.exports` is what actually returns your component.

*BONUS ROUND*: if you're wondering how to get SSR working with `webpack-dev-server`, set the `hot` and `inline` options to `false` in the `devServer` section of your Webpack config, otherwise webpack-dev-server will inject browser code that doesn't work in Node.
